import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { AdressesUtiles } from '../models/adresseUtil.model'; 
import { de } from 'date-fns/locale';

@Injectable({
  providedIn: 'root',
})
export class AdressesUtilesService {
  private addresses: AdressesUtiles[] = [
    {
      id: '341',
      translations: {
        designation: 'Anapec',
        descriptif:
          '<p><a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">Wikipédia</a>&nbsp;est un projet d’encyclopédie collective en ligne, universelle, multilingue et fonctionnant sur le principe du&nbsp;<a href="https://fr.wikipedia.org/wiki/Wiki" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">wiki</a>. Ce projet vise à offrir un contenu librement réutilisable, objectif et vérifiable, que chacun peut modifier et améliorer.</p><p>Wikipédia est définie par des&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Principes_fondateurs" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">principes fondateurs</a>. Son contenu est sous&nbsp;<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">licence&nbsp;Creative Commons BY-SA</a>. Il peut être&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Citation_et_r%C3%A9utilisation_du_contenu_de_Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">copié et réutilisé sous la même licence</a>, sous réserve d\'en respecter les conditions. Wikipédia fournit tous ses contenus gratuitement, sans publicité, et sans recourir à l\'exploitation des données personnelles de ses utilisateurs.</p>',
      },

      adresse: '123 Tangier Street',
      logo: 'assets/images/Sans titre.png',
      image: ['tangier-image1.jpg', 'tangier-image2.jpg'],
      telephones: ['0699281250','0700271534'],
      ville: 'Tangier',
      region: 'Tangier-Tétouan-Al Hoceïma',
      province: 'Tangier-Assilah',
      pays: 'Morocco',
      codePostal: '90000',
      fax: '555-1234',
      email: 'tangier@example.com',
      siteweb: 'http://www.tangier.com',
      addressUtilesPrincipale: null,
      addressUtilesAssocie: [],
      latitude: '35.7678',
      longitude: '-5.8031',
      Horaire: [
        {
          _id: '3',
          AdressesUtiles: '1',
          DayDebut: 'Lundi',
          Dayfin: 'Jeudi',
          heurDebut: '9 AM',
          heurFin: '5 PM',
          DateDebut: new Date('2023-01-01T09:00:00'),
          DateFin: new Date('2023-01-01T17:00:00'),
        },
        // Add more Horaire objects as needed
      ],
      cordonnee: [
        {
          _id: '7',
          refCordonne: '12345',
          pays: 'United States',
          region: 'Tanger assilah',
          ZoneUrbaineRurale: 'Urban',
          villePrincipale: 'Tanger',
          commune: 'Example Commune',
          quartier: 'Example Quartier',
          cp: '12345',
          adress: '123 Example Street',
          latitude: 35.544361279345125,
          longitude: -5.969926866253703,
          translations: {
            description: 'Example Description',
          },
          planAcces: 'Example Plan Access',
          Horaire: [
            {
              _id: '3',
              AdressesUtiles: '1',
              DayDebut: 'Lundi',
              Dayfin: 'Samedi',
              heurDebut: '9 AM',
              heurFin: '5 PM',
              DateDebut: new Date('2023-01-01T09:00:00'),
              DateFin: new Date('2023-01-01T17:00:00'),
            },
            // Add more Horaire objects as needed
          ],
          tel: '123-456-7890',
          Mobile: '987-654-3210',
          fax: '555-1234',
          email: 'example@email.com',
          web: 'www.example.com',
          EtatCoord: 1,
        },
        {
          _id: '8',
          refCordonne: '12345',
          pays: 'United States',
          region: 'Tanger assilah',
          ZoneUrbaineRurale: 'Urban',
          villePrincipale: 'Casablanca',
          commune: 'Example Commune',
          quartier: 'Drissia',
          cp: '12345',
          adress: 'Drissia Tanger ,Maroc',
          latitude: 35.805513289495735,
          longitude: -5.4504517487518385,
          translations: {
            description: '_id 2 ',
          },
          planAcces: 'Example Plan Access',
          Horaire: [
            {
              _id: '3',
              AdressesUtiles: '1',
              DayDebut: 'Lundi',
              Dayfin: 'Jeudi',
              heurDebut: '9 AM',
              heurFin: '5 PM',
              DateDebut: new Date('2023-01-01T09:00:00'),
              DateFin: new Date('2023-01-01T17:00:00'),
            },
          ],
          tel: '123-456-7890',
          Mobile: '987-654-3210',
          fax: '555-1234',
          email: 'example@email.com',
          web: 'www.example.com',
          EtatCoord: 1,
        },
        {
          _id: '9',
          refCordonne: '12345',
          pays: 'United States',
          region: 'agadir',
          ZoneUrbaineRurale: 'Urban',
          villePrincipale: 'agadir',
          commune: 'Example Commune',
          quartier: 'Hamama',
          cp: '12345',
          adress: 'tetouan,Maroc',
          latitude: 35.572957288136365,
          longitude: -5.35077455943199,
          translations: {
            description: '_id 2 ',
          },
          planAcces: 'Example Plan Access',
          tel: '123-456-7890',
          Mobile: '987-654-3210',
          fax: '555-1234',
          email: 'example@email.com',
          web: 'www.example.com',
          EtatCoord: 1,
          Horaire: [
            {
              _id: '3',
              AdressesUtiles: '1',
              DayDebut: 'Lundi',
              Dayfin: 'Jeudi',
              heurDebut: '9 AM',
              heurFin: '5 PM',
              DateDebut: new Date('2023-01-01T09:00:00'),
              DateFin: new Date('2023-01-01T17:00:00'),
            },
          ],
        },
      ],
      ContenuMMedia: [
        {
          file :'',
          typeContenu : '',
          taxonomyContenu: 'Example Taxonomy',
          refContenu: '12345',
          FormatDoc: 'PDF',
          translations: {
            titreDoc: 'Example Document',
            SousTitre: 'Subtitle',
            resume: 'Summary of the document',
          },
          image: 'example-image.jpg',
          Date: new Date('14-12-2024'),
          Auteurs: ['John Doe', 'Alvares'],
          lienContenu: 'https://example.com/document',
          langueParDefaut: 'en',
          Telechargeable: true,
          tailleDoc: 1024,
          TailleLimmite: 2048,
          uniteTaille: 'KB',
          provenanceInterne: true,
          Payant: false,
          DroitLibre: true,
          DroitPublication: true,
          publicationAutorisee: true,
          preuveDroitSiNonLibre: 'Example proof',
        },
      ],
      servicefourni: [
        {
          id: '2341',
          translations: {
            designation: 'Example Designation ',
            description:
              '<p><a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">Wikipédia</a>&nbsp;est un projet d’encyclopédie collective en ligne, universelle, multilingue et fonctionnant sur le principe du&nbsp;<a href="https://fr.wikipedia.org/wiki/Wiki" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">wiki</a>. Ce projet vise à offrir un contenu librement réutilisable, objectif et vérifiable, que chacun peut modifier et améliorer.</p><p>Wikipédia est définie par des&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Principes_fondateurs" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">principes fondateurs</a>. Son contenu est sous&nbsp;<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">licence&nbsp;Creative Commons BY-SA</a>. Il peut être&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Citation_et_r%C3%A9utilisation_du_contenu_de_Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">copié et réutilisé sous la même licence</a>, sous réserve d\'en respecter les conditions. Wikipédia fournit tous ses contenus gratuitement, sans publicité, et sans recourir à l\'exploitation des données personnelles de ses utilisateurs.</p>',
          },
          image: '../../../assets/images/single_service_02.jpg',
          indication_tarifaire: 'Example tariff information',
          indication_horaire: {
            _id: '2343',
            AdressesUtiles: '1',
            DayDebut: 'Lundi',
            Dayfin: 'Jeudi',
            heurDebut: '9 AM',
            heurFin: '5 PM',
            DateDebut: new Date('2023-01-01T09:00:00'),
            DateFin: new Date('2023-01-01T17:00:00'),
          },
          // Add more Horaire objects as needed

          indicationPiece: [  
            {
              id: '4561',
              etatDePublication: 'Published',
              etatobjet: 'Some State',
              taxonomieGeographique: ['Location 1', 'Location 2'],
              taxonomie: 'Taxonomy',
              translations: {
                language: 'en',
                designation: 'PASSPORT MAROC',
                description: 'Un passeport marocain (en arabe : جواز سفر مغربي) est un passeport délivré aux citoyens marocains pour les voyages internationaux.Le royaume du Maroc a mis en circulation depuis le 15 décembre 2009 un passeport biométrique, conforme aux recommandations de l’Organisation de l\'aviation civile internationale.',
              },
              image: '../../../assets/images/passeportMaroc.jpg',
              formatDelivrance: 'Papier',
              payant: true,
              tarifMoyenne: 20,
              delaiMoyenObtention: 7,
              uniteDelai: 'Days',
              typeDureeValidite: 'code_209',
              dureeValidite: 30,
              uniteDureeValidite: 'Days',
              objetAssocie: ['Object 1', 'Object 2'],
              conditionDelivrance: ['Condition 1', 'Condition 2'],
              etats: ['State 1', 'State 2'],
              createdAt: new Date(),
              updatedAt: new Date(),
              procedures: [
                {
                  id: '2352341',
                  etatobjet: 'Some State',
                  numEtape: 1,
                  translations: {
                    language: 'en',
                    designation: 'PASSPORT MAROC etap 1',
                    description:'<p><a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">Wikipédia</a>&nbsp;est un projet d’encyclopédie collective en ligne, universelle, multilingue et fonctionnant sur le principe du&nbsp;<a href="https://fr.wikipedia.org/wiki/Wiki" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">wiki</a>. Ce projet vise à offrir un contenu librement réutilisable, objectif et vérifiable, que chacun peut modifier et améliorer.</p><p>Wikipédia est définie par des&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Principes_fondateurs" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">principes fondateurs</a>. Son contenu est sous&nbsp;<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">licence&nbsp;Creative Commons BY-SA</a>. Il peut être&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Citation_et_r%C3%A9utilisation_du_contenu_de_Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">copié et réutilisé sous la même licence</a>, sous réserve d\'en respecter les conditions. Wikipédia fournit tous ses contenus gratuitement, sans publicité, et sans recourir à l\'exploitation des données personnelles de ses utilisateurs.</p>',
                  },
                  pieceEtDoc: '1',
                  objetsAssocies: ['Object 1', 'Object 2'],
                  createdAt: new Date(),
                  updatedAt: new Date(),
                },
                {
                  id: '23543452',
                  etatobjet: 'Some State',
                  numEtape: 1,
                  translations: {
                    language: 'en',
                    designation: 'PASSPORT MAROC etap 2',
                    description:'<p><a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">Wikipédia</a>&nbsp;est un projet d’encyclopédie collective en ligne, universelle, multilingue et fonctionnant sur le principe du&nbsp;<a href="https://fr.wikipedia.org/wiki/Wiki" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">wiki</a>. Ce projet vise à offrir un contenu librement réutilisable, objectif et vérifiable, que chacun peut modifier et améliorer.</p><p>Wikipédia est définie par des&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Principes_fondateurs" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">principes fondateurs</a>. Son contenu est sous&nbsp;<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">licence&nbsp;Creative Commons BY-SA</a>. Il peut être&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Citation_et_r%C3%A9utilisation_du_contenu_de_Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">copié et réutilisé sous la même licence</a>, sous réserve d\'en respecter les conditions. Wikipédia fournit tous ses contenus gratuitement, sans publicité, et sans recourir à l\'exploitation des données personnelles de ses utilisateurs.</p>',
                  },
                  pieceEtDoc: '1',
                  objetsAssocies: ['Object 1', 'Object 2'],
                  createdAt: new Date(),
                  updatedAt: new Date(),
                },
                {
                  id: '35423453',
                  etatobjet: 'Some State',
                  numEtape: 1,
                  translations: {
                    language: 'en',
                    designation: 'PASSPORT MAROC etap 3',
                    description:'<p><a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">Wikipédia</a>&nbsp;est un projet d’encyclopédie collective en ligne, universelle, multilingue et fonctionnant sur le principe du&nbsp;<a href="https://fr.wikipedia.org/wiki/Wiki" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">wiki</a>. Ce projet vise à offrir un contenu librement réutilisable, objectif et vérifiable, que chacun peut modifier et améliorer.</p><p>Wikipédia est définie par des&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Principes_fondateurs" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">principes fondateurs</a>. Son contenu est sous&nbsp;<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">licence&nbsp;Creative Commons BY-SA</a>. Il peut être&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Citation_et_r%C3%A9utilisation_du_contenu_de_Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">copié et réutilisé sous la même licence</a>, sous réserve d\'en respecter les conditions. Wikipédia fournit tous ses contenus gratuitement, sans publicité, et sans recourir à l\'exploitation des données personnelles de ses utilisateurs.</p>',
                  },
                  pieceEtDoc: '1',
                  objetsAssocies: ['Object 1', 'Object 2'],
                  createdAt: new Date(),
                  updatedAt: new Date(),
                },
                {
                  id: '35423453',
                  etatobjet: 'Some State',
                  numEtape: 1,
                  translations: {
                    language: 'en',
                    designation: 'PASSPORT MAROC etap 3',
                    description:'<p><a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">Wikipédia</a>&nbsp;est un projet d’encyclopédie collective en ligne, universelle, multilingue et fonctionnant sur le principe du&nbsp;<a href="https://fr.wikipedia.org/wiki/Wiki" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">wiki</a>. Ce projet vise à offrir un contenu librement réutilisable, objectif et vérifiable, que chacun peut modifier et améliorer.</p><p>Wikipédia est définie par des&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Principes_fondateurs" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">principes fondateurs</a>. Son contenu est sous&nbsp;<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">licence&nbsp;Creative Commons BY-SA</a>. Il peut être&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Citation_et_r%C3%A9utilisation_du_contenu_de_Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">copié et réutilisé sous la même licence</a>, sous réserve d\'en respecter les conditions. Wikipédia fournit tous ses contenus gratuitement, sans publicité, et sans recourir à l\'exploitation des données personnelles de ses utilisateurs.</p>',
                  },
                  pieceEtDoc: '1',
                  objetsAssocies: ['Object 1', 'Object 2'],
                  createdAt: new Date(),
                  updatedAt: new Date(),
                },
                {
                  id: '35423453',
                  etatobjet: 'Some State',
                  numEtape: 1,
                  translations: {
                    language: 'en',
                    designation: 'PASSPORT MAROC etap 3',
                    description:'<p><a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">Wikipédia</a>&nbsp;est un projet d’encyclopédie collective en ligne, universelle, multilingue et fonctionnant sur le principe du&nbsp;<a href="https://fr.wikipedia.org/wiki/Wiki" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">wiki</a>. Ce projet vise à offrir un contenu librement réutilisable, objectif et vérifiable, que chacun peut modifier et améliorer.</p><p>Wikipédia est définie par des&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Principes_fondateurs" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">principes fondateurs</a>. Son contenu est sous&nbsp;<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">licence&nbsp;Creative Commons BY-SA</a>. Il peut être&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Citation_et_r%C3%A9utilisation_du_contenu_de_Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">copié et réutilisé sous la même licence</a>, sous réserve d\'en respecter les conditions. Wikipédia fournit tous ses contenus gratuitement, sans publicité, et sans recourir à l\'exploitation des données personnelles de ses utilisateurs.</p>',
                  },
                  pieceEtDoc: '1',
                  objetsAssocies: ['Object 1', 'Object 2'],
                  createdAt: new Date(),
                  updatedAt: new Date(),
                },
                {
                  id: '35423453',
                  etatobjet: 'Some State',
                  numEtape: 1,
                  translations: {
                    language: 'en',
                    designation: 'PASSPORT MAROC etap 3',
                    description:'<p><a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">Wikipédia</a>&nbsp;est un projet d’encyclopédie collective en ligne, universelle, multilingue et fonctionnant sur le principe du&nbsp;<a href="https://fr.wikipedia.org/wiki/Wiki" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">wiki</a>. Ce projet vise à offrir un contenu librement réutilisable, objectif et vérifiable, que chacun peut modifier et améliorer.</p><p>Wikipédia est définie par des&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Principes_fondateurs" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">principes fondateurs</a>. Son contenu est sous&nbsp;<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">licence&nbsp;Creative Commons BY-SA</a>. Il peut être&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Citation_et_r%C3%A9utilisation_du_contenu_de_Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">copié et réutilisé sous la même licence</a>, sous réserve d\'en respecter les conditions. Wikipédia fournit tous ses contenus gratuitement, sans publicité, et sans recourir à l\'exploitation des données personnelles de ses utilisateurs.</p>',
                  },
                  pieceEtDoc: '1',
                  objetsAssocies: ['Object 1', 'Object 2'],
                  createdAt: new Date(),
                  updatedAt: new Date(),
                },
                {
                  id: '35423453',
                  etatobjet: 'Some State',
                  numEtape: 1,
                  translations: {
                    language: 'en',
                    designation: 'PASSPORT MAROC etap 3',
                    description:'<p><a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">Wikipédia</a>&nbsp;est un projet d’encyclopédie collective en ligne, universelle, multilingue et fonctionnant sur le principe du&nbsp;<a href="https://fr.wikipedia.org/wiki/Wiki" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">wiki</a>. Ce projet vise à offrir un contenu librement réutilisable, objectif et vérifiable, que chacun peut modifier et améliorer.</p><p>Wikipédia est définie par des&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Principes_fondateurs" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">principes fondateurs</a>. Son contenu est sous&nbsp;<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">licence&nbsp;Creative Commons BY-SA</a>. Il peut être&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Citation_et_r%C3%A9utilisation_du_contenu_de_Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">copié et réutilisé sous la même licence</a>, sous réserve d\'en respecter les conditions. Wikipédia fournit tous ses contenus gratuitement, sans publicité, et sans recourir à l\'exploitation des données personnelles de ses utilisateurs.</p>',
                  },
                  pieceEtDoc: '1',
                  objetsAssocies: ['Object 1', 'Object 2'],
                  createdAt: new Date(),
                  updatedAt: new Date(),
                },
              ],
              condition: [
                {
                  _id: '1234567890',
                  piece: '4561',
                  code_type: 'CIN',
                  operateur: '',
                  valeurS: 'Maroccain',
                  unite_de_valeur: '',
                },
                {
                  _id: '1234567890',
                  piece: '4561',
                  code_type: 'age',
                  operateur: '',
                  valeurS: "il y ' a pas d'une condition d'age ",
                  unite_de_valeur: '',
                },
              ],
              pieceAssocie: [ 
                {
                  id: '123456789',
                  etatDePublication: 'Published',
                  etatobjet: 'Some State',
                  taxonomieGeographique: ['Location 3', 'Location 4'],
                  taxonomie: 'Taxonomy 2',
                  translations: {
                    language: 'en',
                    designation: 'Object 1',
                    description: 'Object Description 1',
                  },
                  image: '../../../assets/images/equipe.jpg',
                  formatDelivrance: 'Papier',
                  payant: false,
                  tarifMoyenne: 15,
                  delaiMoyenObtention: 5,
                  uniteDelai: 'Days',
                  typeDureeValidite: 'code_210',
                  dureeValidite: 60,
                  uniteDureeValidite: 'Days',
                  objetAssocie: ['Associated Object 1', 'Associated Object 2'],
                  conditionDelivrance: ['Condition 3', 'Condition 4'],
                  etats: ['State 3', 'State 4'],
                  createdAt: new Date(),
                  updatedAt: new Date(),
                  procedures: [
                    {
                      id: '78901234',
                      etatobjet: 'Some State',
                      numEtape: 1,
                      translations: {
                        language: 'en',
                        designation: 'Object 1 etap 1',
                        description:'<p><a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">Wikipédia</a>&nbsp;est un projet d’encyclopédie collective en ligne, universelle, multilingue et fonctionnant sur le principe du&nbsp;<a href="https://fr.wikipedia.org/wiki/Wiki" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">wiki</a>. Ce projet vise à offrir un contenu librement réutilisable, objectif et vérifiable, que chacun peut modifier et améliorer.</p><p>Wikipédia est définie par des&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Principes_fondateurs" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">principes fondateurs</a>. Son contenu est sous&nbsp;<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">licence&nbsp;Creative Commons BY-SA</a>. Il peut être&nbsp;<a href="https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Citation_et_r%C3%A9utilisation_du_contenu_de_Wikip%C3%A9dia" rel="noopener noreferrer" target="_blank" style="background-color: initial; color: rgb(51, 102, 204);">copié et réutilisé sous la même licence</a>, sous réserve d\'en respecter les conditions. Wikipédia fournit tous ses contenus gratuitement, sans publicité, et sans recourir à l\'exploitation des données personnelles de ses utilisateurs.</p>',
                      },
                      pieceEtDoc: '123456789',
                      objetsAssocies: ['Associated Object 1', 'Associated Object 2'],
                      createdAt: new Date(),
                      updatedAt: new Date(),
                    },
                  ],
                  condition: [
                    {
                      _id: '1234567890',
                      piece: '123456789',
                      code_type: 'Type 1',
                      operateur: '',
                      valeurS: 'Value 1',
                      unite_de_valeur: '',
                    },
                    {
                      _id: '0987654321',
                      piece: '123456789',
                      code_type: 'Type 2',
                      operateur: '',
                      valeurS: 'Value 2',
                      unite_de_valeur: '',
                    },
                  ],
                  instancePiece:[{
                    type: 'ExampleType',
                    refPiece: 'parent12345', // Parent piece ID as a string
                    translations: {
                      language: 'en',
                      designation: 'Example InstancePiece',
                      description: 'Example InstancePiece Description',
                    },
                    nbrOriginale: 2,
                    nbrCopieConforme: 3,
                    nbrCompieSimple: 1,
                    typeDureeValidite: 'code_209',
                    dureeValidite: 15,
                    uniteTemps: 'Days',
                    indicationTarifaire: 25,
                    monnaire: 'USD',
                    demarcheObtention: 'Example Obtention Process',
                    demarche: 'Example Procedure',
                    
                    objetAssocie: 'Example Associated Object',
                  }]
                },
                // Add more associated objects as needed
              ],
              instancePiece:[
                {
                  type: 'ExampleType',
                  refPiece: 'parent12345', // Parent piece ID as a string
                  translations: {
                    language: 'en',
                    designation: 'Photo',
                    description: 'Four (4) passport size photographs',
                  },
                  nbrOriginale: 4,
                  nbrCopieConforme: 0,
                  nbrCompieSimple: 4,
                  typeDureeValidite: 'code_209',
                  dureeValidite: 0,
                  uniteTemps: 'Days',
                  indicationTarifaire: 25,
                  monnaire: 'USD',
                  demarcheObtention: 'Example Obtention Process',
                  demarche: 'Example Procedure',
                  adressUtiles: '341',
                  objetAssocie: 'Example Associated Object',
                },
                {
                  type: 'ExampleType',
                  refPiece: 'parent12345', // Parent piece ID as a string
                  translations: {
                    language: 'en',
                    designation: 'Copy of birth certificate',
                    description: ' (in Arabic and in French) issued within the last three months ;',
                  },
                  nbrOriginale: 1,
                  nbrCopieConforme: 0,
                  nbrCompieSimple: 1,
                  typeDureeValidite: 'code_207',
                  dureeValidite: 3,
                  uniteTemps: 'months',
                  indicationTarifaire: 20,
                  monnaire: 'MAD',
                  demarcheObtention: 'Example Obtention Process',
                  demarche: 'Example Procedure',
                  adressUtiles: '341',
                  objetAssocie: 'Example Associated Object',
                },
              ]
            },  
                      
            {
              id: '23532535',
              etatDePublication: 'Published',
              etatobjet: 'Some State',
              taxonomieGeographique: ['Location 1', 'Location 2'],
              taxonomie: 'Taxonomy',
              translations: {
                language: 'en',
                designation: 'CIN MAROC',
                description: 'Document Description2',
              },
              image: '../../../assets/images/CIN_maroc.jpg',
              formatDelivrance: 'Numerique',
              payant: true,
              tarifMoyenne: 20,
              delaiMoyenObtention: 7,
              uniteDelai: 'Days',
              typeDureeValidite: 'code_207',
              dureeValidite: 30,
              uniteDureeValidite: 'Days',
              objetAssocie: ['Object 1', 'Object 2'],
              conditionDelivrance: ['Condition 1', 'Condition 2'],
              etats: ['State 1', 'State 2'],
              createdAt: new Date(),
              updatedAt: new Date(),
              procedures: [
                {
                  id: '1235425',
                  etatobjet: 'teeeeest',
                  numEtape: 1,
                  translations: {
                    language: 'en',
                    designation: 'Procedure Name',
                    description: 'Procedure Description',
                  },
                  pieceEtDoc: '1',
                  objetsAssocies: ['Object 1', 'Object 2'],
                  createdAt: new Date(),
                  updatedAt: new Date(),
                },
              ],
              condition: [
                {
                  _id: '1234567890',
                  piece: '23532535',
                  code_type: 'age',
                  operateur: '>',
                  valeurS: '18',
                  unite_de_valeur: 'ans',
                },
                {
                  _id: '12345678ab90',
                  piece: '23532535',
                  code_type: 'Nationalite',
                  operateur: '',
                  valeurS: 'Maroccain',
                  unite_de_valeur: '',
                },
              ],
              instancePiece:[]
            },
          ],
        },
        {
          id: '2325235235',
          translations: {
            designation: 'Example Designation',
            description: 'Example Description',
          },
          image: '../../../assets/images/single_service_02.jpg',
          indication_tarifaire: 'Example tariff information',
          indication_horaire: {
            _id: '33245235235',
            AdressesUtiles: '1',
            DayDebut: 'Lundi',
            Dayfin: 'Jeudi',
            heurDebut: '9 AM',
            heurFin: '5 PM',
            DateDebut: new Date('2023-01-01T09:00:00'),
            DateFin: new Date('2023-01-01T17:00:00'),
          },
          indicationPiece: [
            {
              id: '232525235',
              etatDePublication: 'Published',
              etatobjet: 'Some State',
              taxonomieGeographique: ['Location 1', 'Location 2'],
              taxonomie: 'Taxonomy',
              translations: {
                language: 'en',
                designation: 'Document Name',
                description: 'Document Description',
              },
              image: '../../../assets/images/team_02.jpg',
              formatDelivrance: 'Numerique',
              payant: true,
              tarifMoyenne: 20,
              delaiMoyenObtention: 7,
              uniteDelai: 'Days',
              typeDureeValidite: 'Temporary',
              dureeValidite: 30,
              uniteDureeValidite: 'Days',
              objetAssocie: ['Object 1', 'Object 2'],
              conditionDelivrance: ['Condition 1', 'Condition 2'],
              etats: ['State 1', 'State 2'],
              createdAt: new Date(),
              updatedAt: new Date(),
              procedures: [
                {
                  id: '3325325  ',
                  etatobjet: 'Some State',
                  numEtape: 1,
                  translations: {
                    language: 'en',
                    designation: 'Procedure Name',
                    description: 'Procedure Description',
                  },
                  pieceEtDoc: '2',
                  objetsAssocies: ['Object 1', 'Object 2'],
                  createdAt: new Date(),
                  updatedAt: new Date(),
                },
              ],
              condition: [
                {
                  _id: '1234567890',
                  piece: '23532535',
                  code_type: 'example_code_type',
                  operateur: 'example_operator',
                  valeurS: 'example_value',
                  unite_de_valeur: 'example_unit',
                },
              ],
              instancePiece : []
            },
          ],
        },
      ],
    },
  ];

  getAddresses(): Observable<AdressesUtiles[]> {
    return of(this.addresses);
  }

  getAddressById(id: string): Observable<AdressesUtiles | undefined> {
    const selectedAddress = this.addresses.find((a) => a.id === id);
    return of(selectedAddress);
  }
}
