import { Injectable } from "@angular/core";
import { domain } from "../models/domain.model";

@Injectable({
  providedIn: "root",
})
export class domainService {
  private domain: domain[] = [];

  constructor() {
    this.domain = [
      {
        _id: "12387928742877",
        translations: {
          language: "en",
          designation: "problem avec une achat",
          description: "Description",
        },
        logo: "bi bi-building",
        code: "code123",
        parent: null,
        children: [],
        taxonomies: [
          {
            _id: "1",
            translations: {
              language: "en",
              designation: "Mauvais emballage",
              description: "This is the first taxonomy",
            },
            logo: "logo1.png",
            code: "T1",
            parent: null,
            children: [],
            domain: "",
            caracteristique: [],
            hasTaxonomies: false,
            etatObjet: "code-1",
            etatCreation: "created",
            dateEnregistrement: new Date().toISOString(),
          },
          {
            _id: "2",
            translations: {
              language: "en",
              designation: "not the product u want",
              description: "This is the first taxonomy",
            },
            logo: "logo1.png",
            code: "T1",
            parent: null,
            children: [],
            domain: "",
            caracteristique: [],
            hasTaxonomies: false,
            etatObjet: "code-1",
            etatCreation: "created",
            dateEnregistrement: new Date().toISOString(),
          },
          {
            _id: "3",
            translations: {
              language: "en",
              designation: "broken product",
              description: "This is the first taxonomy",
            },
            logo: "logo1.png",
            code: "T1",
            parent: null,
            children: [],
            domain: "",
            caracteristique: [],
            hasTaxonomies: false,
            etatObjet: "code-1",
            etatCreation: "created",
            dateEnregistrement: new Date().toISOString(),
          },
        ],
        groupe: [],
        hasTaxonomies: true,
        etatObjet: "code-1",
        etatCreation: "created",
        dateEnregistrement: new Date().toISOString(),
      },
      {
        _id: "2",
        translations: {
          language: "en",
          designation: "problem avec qlq un",
          description: "Description",
        },
        logo: "bi bi-building",
        code: "code123",
        parent: null,
        children: [],
        taxonomies: [
          {
            _id: "1",
            translations: {
              language: "en",
              designation: "avec securite",
              description: "This is the first taxonomy",
            },
            logo: "logo1.png",
            code: "T1",
            parent: null,
            children: [],
            domain: "",
            caracteristique: [],
            hasTaxonomies: false,
            etatObjet: "code-1",
            etatCreation: "created",
            dateEnregistrement: new Date().toISOString(),
          },
          {
            _id: "2",
            translations: {
              language: "en",
              designation: "avec support",
              description: "This is the first taxonomy",
            },
            logo: "logo1.png",
            code: "T1",
            parent: null,
            children: [],
            domain: "",
            caracteristique: [],
            hasTaxonomies: false,
            etatObjet: "code-1",
            etatCreation: "created",
            dateEnregistrement: new Date().toISOString(),
          },
          {
            _id: "3",
            translations: {
              language: "en",
              designation: "avec secretere",
              description: "This is the first taxonomy",
            },
            logo: "logo1.png",
            code: "T1",
            parent: null,
            children: [],
            domain: "",
            caracteristique: [],
            hasTaxonomies: false,
            etatObjet: "code-1",
            etatCreation: "created",
            dateEnregistrement: new Date().toISOString(),
          },
        ],
        groupe: [],
        hasTaxonomies: true,
        etatObjet: "code-1",
        etatCreation: "created",
        dateEnregistrement: new Date().toISOString(),
      },
      {
        _id: "123879287428774334",
        translations: {
          language: "en",
          designation: "problem avec une achat",
          description: "Description",
        },
        logo: "bi bi-building",
        code: "code_535",
        parent: null,
        children: [],
        taxonomies: [
          {
            _id: "4441",
            translations: {
              language: "en",
              designation: "Mauvais emballage",
              description: "This is the first taxonomy",
            },
            logo: "logo1.png",
            code: "T1",
            parent: null,
            children: [],
            domain: "",
            caracteristique: [],
            hasTaxonomies: false,
            etatObjet: "code-1",
            etatCreation: "created",
            dateEnregistrement: new Date().toISOString(),
          },
          {
            _id: "33332",
            translations: {
              language: "en",
              designation: "not the product u want",
              description: "This is the first taxonomy",
            },
            logo: "logo1.png",
            code: "T1",
            parent: null,
            children: [],
            domain: "",
            caracteristique: [],
            hasTaxonomies: false,
            etatObjet: "code-1",
            etatCreation: "created",
            dateEnregistrement: new Date().toISOString(),
          },
          {
            _id: "44443",
            translations: {
              language: "en",
              designation: "broken product",
              description: "This is the first taxonomy",
            },
            logo: "logo1.png",
            code: "T1",
            parent: null,
            children: [],
            domain: "",
            caracteristique: [],
            hasTaxonomies: false,
            etatObjet: "code-1",
            etatCreation: "created",
            dateEnregistrement: new Date().toISOString(),
          },
        ],
        groupe: [],
        hasTaxonomies: true,
        etatObjet: "code-1",
        etatCreation: "created",
        dateEnregistrement: new Date().toISOString(),
      },
      {
        _id: "24",
        translations: {
          language: "en",
          designation: "problem avec qlq un",
          description: "Description",
        },
        logo: "bi bi-building",
        code: "code_536",
        parent: null,
        children: [],
        taxonomies: [
          {
            _id: "1weefwf",
            translations: {
              language: "en",
              designation: "avec securite",
              description: "This is the first taxonomy",
            },
            logo: "logo1.png",
            code: "T1",
            parent: null,
            children: [],
            domain: "",
            caracteristique: [],
            hasTaxonomies: false,
            etatObjet: "code-1",
            etatCreation: "created",
            dateEnregistrement: new Date().toISOString(),
          },
          {
            _id: "2sgfdghgfh",
            translations: {
              language: "en",
              designation: "avec support",
              description: "This is the first taxonomy",
            },
            logo: "logo1.png",
            code: "T1",
            parent: null,
            children: [],
            domain: "",
            caracteristique: [],
            hasTaxonomies: false,
            etatObjet: "code-1",
            etatCreation: "created",
            dateEnregistrement: new Date().toISOString(),
          },
          {
            _id: "3fsghsfgt",
            translations: {
              language: "en",
              designation: "avec secretere",
              description: "This is the first taxonomy",
            },
            logo: "logo1.png",
            code: "T1",
            parent: null,
            children: [],
            domain: "",
            caracteristique: [],
            hasTaxonomies: false,
            etatObjet: "code-1",
            etatCreation: "created",
            dateEnregistrement: new Date().toISOString(),
          },
        ],
        groupe: [],
        hasTaxonomies: true,
        etatObjet: "code-1",
        etatCreation: "created",
        dateEnregistrement: new Date().toISOString(),
      },
      {
        _id: "4343434rr",
        translations: {
          language: "en",
          designation: "E-service",
          description: "Description",
        },
        logo: "bi bi-building",
        code: "code_536",
        parent: null,
        children: [],
        taxonomies: [
          {
            _id: "212312312313",
            translations: {
              language: "en",
              designation: "Reservation d'une table",
              description: "taxo",
            },
            logo: "assets/images/reservation.jpg",
            code: "T1",
            parent: null,
            children: [],
            domain: "40995094",
            caracteristique: [],
            hasTaxonomies: false,
            etatObjet: "code-1",
            etatCreation: "created",
            dateEnregistrement: new Date().toISOString(),
          },
          {
            _id: "1231231231232",
            translations: {
              language: "en",
              designation: "Reservation d'une chambre",
              description: "taxo",
            },
            logo: "assets/images/reservation.jpg",
            code: "T1",
            parent: null,
            children: [],
            domain: "40995094",
            caracteristique: [],
            hasTaxonomies: false,
            etatObjet: "code-1",
            etatCreation: "created",
            dateEnregistrement: new Date().toISOString(),
          },
          {
            _id: "21231234234",
            translations: {
              language: "en",
              designation: "Reservation d'une voiture",
              description: "taxo",
            },
            logo: "assets/images/reservation.jpg",
            code: "T1",
            parent: null,
            children: [],
            domain: "40995094",
            caracteristique: [],
            hasTaxonomies: false,
            etatObjet: "code-1",
            etatCreation: "created",
            dateEnregistrement: new Date().toISOString(),
          },
        ],
        groupe: [],
        hasTaxonomies: true,
        etatObjet: "code-1",
        etatCreation: "created",
        dateEnregistrement: new Date().toISOString(),
      },
    ];
  }
  getDomains(): domain[] {
    return this.domain;
  }

  getDomainById(id: "string"): domain | undefined {
    return this.domain.find((d) => d._id === id);
  }
}

