import { Injectable } from '@angular/core';
import { FooterJ } from '../models/footerJ.model';

@Injectable({
  providedIn: 'root'
})
export class FooterJService {

  constructor() { }
  private footer:FooterJ[]=[
    {
      _id:'1',
      translations: {
        language:'fr',
        title:'SERVICES LOGISTIC POST',
      },
      planPrincipale:true,
      megaMenu:true,
      icon:'',
      path:'',
      ordre:1,
      priorite:1,
      typeAffichage:'card',
      parent:'',
      children:[
        {
          _id:'1',
          translations: {
            language:'fr',
            title:'Evénément',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:1,
          priorite:1,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'2',
          translations: {
            language:'fr',
            title:'Actualité',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:2,
          priorite:2,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'3',
          translations: {
            language:'fr',
            title:'Edito',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:3,
          priorite:3,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'4',
          translations: {
            language:'fr',
            title:'Tribune',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:4,
          priorite:4,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'5',
          translations: {
            language:'fr',
            title:'Plaidoyer',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:5,
          priorite:5,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'6',
          translations: {
            language:'fr',
            title:'Pétitions',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:6,
          priorite:6,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'7',
          translations: {
            language:'fr',
            title:'Info Route',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:7,
          priorite:7,
          typeAffichage:'',
          parent:'',
          children:[],
        }
      ],
    },
    {
      _id:'2',
      translations: {
        language:'fr',
        title:'LIENS UTILES',
      },
      planPrincipale:true,
      megaMenu:true,
      icon:'',
      path:'',
      ordre:2,
      priorite:2,
      typeAffichage:'card',
      parent:'',
      children:[
        {
          _id:'1',
          translations: {
            language:'fr',
            title:'Mentions légales',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:1,
          priorite:1,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'2',
          translations: {
            language:'fr',
            title:'Visite Guidée',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:2,
          priorite:2,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'3',
          translations: {
            language:'fr',
            title:'Charte et réglements',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:3,
          priorite:3,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'4',
          translations: {
            language:'fr',
            title:'Politique de confidentialité',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:4,
          priorite:4,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'5',
          translations: {
            language:'fr',
            title:'Gestion des cookies',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:5,
          priorite:5,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'6',
          translations: {
            language:'fr',
            title:'Conditions générales',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:6,
          priorite:6,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'7',
          translations: {
            language:'fr',
            title:'CGU',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:7,
          priorite:7,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'8',
          translations: {
            language:'fr',
            title:'Aide (FAQ)',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:8,
          priorite:8,
          typeAffichage:'',
          parent:'',
          children:[],
        }
      ],
    },
    {
      _id:'3',
      translations: {
        language:'fr',
        title:'NEWSLETTERS',
      },
      planPrincipale:true,
      megaMenu:true,
      icon:'',
      path:'',
      ordre:3,
      priorite:3,
      typeAffichage:'card',
      taxonomie:'code_628',
      parent:'',
      children:[],
    },
    {
      _id:'4',
      translations: {
        language:'fr',
        title:'SERVICES PARTENAIRES',
      },
      planPrincipale:true,
      megaMenu:true,
      icon:'',
      path:'',
      ordre:4,
      priorite:4,
      typeAffichage:'card',
      parent:'',
      children:[
        {
          _id:'1',
          translations: {
            language:'fr',
            title:'Formation professionnelle',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:1,
          priorite:1,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'2',
          translations: {
            language:'fr',
            title:'Formation en audiovisuel',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:2,
          priorite:2,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'3',
          translations: {
            language:'fr',
            title:'Annonces légales',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:3,
          priorite:3,
          typeAffichage:'',
          parent:'',
          children:[],
        },

      ],
    },
    {
      _id:'5',
      translations: {
        language:'fr',
        title:'EMPLOIS & STAGES',
      },
      planPrincipale:true,
      megaMenu:true,
      icon:'',
      path:'',
      ordre:5,
      priorite:5,
      typeAffichage:'card',
      parent:'',
      children:[
        {
          _id:'1',
          translations: {
            language:'fr',
            title:"Offres d'emplois",
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:1,
          priorite:1,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'2',
          translations: {
            language:'fr',
            title:'Offres de stages',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:2,
          priorite:2,
          typeAffichage:'',
          parent:'',
          children:[],
        },
      ],
    },
    {
      _id:'6',
      translations: {
        language:'fr',
        title:'ABONNEMENT',
      },
      planPrincipale:true,
      megaMenu:true,
      icon:'',
      path:'',
      ordre:6,
      priorite:6,
      typeAffichage:'card',
      parent:'',
      children:[
        {
          _id:'1',
          translations: {
            language:'fr',
            title:'Qui sommes nous ?',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:1,
          priorite:1,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'2',
          translations: {
            language:'fr',
            title:'Notre organisation',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:2,
          priorite:2,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'3',
          translations: {
            language:'fr',
            title:'Notre mission',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:3,
          priorite:3,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'4',
          translations: {
            language:'fr',
            title:"S'abonner",
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:4,
          priorite:4,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'5',
          translations: {
            language:'fr',
            title:'Se connecter',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:5,
          priorite:5,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'6',
          translations: {
            language:'fr',
            title:'Évenements abonnés ',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:6,
          priorite:6,
          typeAffichage:'',
          parent:'',
          children:[],
        },
        {
          _id:'7',
          translations: {
            language:'fr',
            title:'Contactez-nous',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'',
          path:'',
          ordre:7,
          priorite:7,
          typeAffichage:'',
          parent:'',
          children:[],
        },
      ],
    },
    {
      _id:'7',
      translations: {
        language:'fr',
        title:'SUIVEZ LOGISTIC POST',
      },
      planPrincipale:true,
      megaMenu:true,
      icon:'',
      path:'',
      ordre:7,
      priorite:7,
      typeAffichage:'full',
      parent:'',
      children:[
        {
          _id:'1',
          translations: {
            language:'fr',
            title:'Facebook',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'bi bi-facebook',
          path:'',
          ordre:1,
          priorite:1,
          typeAffichage:'full',
          parent:'',
          children:[],
        },
        {
          _id:'2',
          translations: {
            language:'fr',
            title:'Instagram',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'bi bi-instagram',
          path:'',
          ordre:2,
          priorite:2,
          typeAffichage:'full',
          parent:'',
          children:[],
        },
        {
          _id:'3',
          translations: {
            language:'fr',
            title:'Twitter',
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'bi bi-twitter',
          path:'',
          ordre:3,
          priorite:3,
          typeAffichage:'full',
          parent:'',
          children:[],
        },
        {
          _id:'4',
          translations: {
            language:'fr',
            title:"Youtube",
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'bi bi-youtube',
          path:'',
          ordre:4,
          priorite:4,
          typeAffichage:'full',
          parent:'',
          children:[],
        },
        {
          _id:'5',
          translations: {
            language:'fr',
            title:"Linkedin",
          },
          planPrincipale:false,
          megaMenu:false,
          icon:'bi bi-linkedin',
          path:'',
          ordre:5,
          priorite:5,
          typeAffichage:'full',
          parent:'',
          children:[],
        },

      ],
    },

  ]
  getAllFooter(){
    this.footer.sort((a, b) => a.ordre - b.ordre);
    this.footer.forEach((children) => {
      children.children.sort((a, b) => a.ordre - b.ordre).forEach((souschildren) => {
        souschildren.children.sort((a, b) => a.ordre - b.ordre)
      });
    });
    return this.footer;
  }
}
