import { Injectable } from '@angular/core';  
import { Menu } from '../models/menu.model';



@Injectable({
  providedIn: 'root',  
})
export class menuService {
  private menu : Menu[] = []; 

  constructor() {
    this.menu = [{
                    _id: '1',
                    translations: {
                      language: 'string',
                      title: 'code_8806',
                    },
                    planPrincipal: false,
                    megaMenu: true,
                    icon: "fas fa-tractor",
                    path: 'string',
                    taxonomy : 'code_8806',
                    ordre: 0,
                    priorite: 0,
                    parent: null ,
                    children: [
                      {
                                _id: '1',
                                translations: {
                                  language: 'string',
                                  title: 'code_476',
                                },
                                planPrincipal: false,
                                megaMenu: false,
                                icon: 'string',
                                path: 'string',
                                taxonomy : 'code_476',
                                ordre: 0,
                                priorite: 0,
                                parent: null ,
                                children: [],
                                },
                                {
                                  _id: '2',
                                translations: {
                                  language: 'string',
                                  title: 'code_477',
                                },
                                planPrincipal: false,
                                megaMenu: false,
                                icon: 'string',
                                path: 'string',
                                taxonomy : 'code_477',
                                ordre: 0,
                                priorite: 0,
                                parent: null ,
                                children: [],
                                },
                                {
                                  _id: '3',
                                translations: {
                                  language: 'string',
                                  title: 'code_478',
                                },
                                planPrincipal: false,
                                megaMenu: false,
                                icon: 'string',
                                path: 'string',
                                taxonomy : 'code_478',
                                ordre: 0,
                                priorite: 0,
                                parent: null ,
                                children: [],
                              },
                              {
                                _id: '4',
                              translations: {
                                language: 'string',
                                title: 'code_479',
                              },
                              planPrincipal: false,
                              megaMenu: false,
                              icon: 'string',
                              path: 'string',
                              ordre: 0,
                              priorite: 0,
                              taxonomy : 'code_479',
                              parent: null ,
                              children: [],
                              },
                              {
                                _id: '5',
                              translations: {
                                language: 'string',
                                title: 'code_480',
                              },
                              planPrincipal: false,
                              megaMenu: false,
                              icon: 'string',
                              path: 'string',
                              taxonomy : 'code_480',
                              ordre: 0,
                              priorite: 0,
                              parent: null ,
                              children: [],
                              }
                  ],
                 },
                 {
                  _id: '2',
                  translations: {
                    language: 'string',
                    title: 'code_8807',
                  },
                  planPrincipal: false,
                  megaMenu: false,
                  icon: 'fa-solid fa-person-digging',
                  path: 'string',
                  taxonomy : 'code_8807',
                  ordre: 0,
                  priorite: 0,
                  parent: null ,
                  children: [],
                },
                {
                  _id: '3',
                  translations: {
                    language: 'string',
                    title: 'code_8808',
                  },
                  planPrincipal: false,
                  megaMenu: false,
                  icon: 'fa-solid fa-solar-panel',
                  path: 'string',
                  taxonomy : 'code_8808',
                  ordre: 0,
                  priorite: 0,
                  parent: null ,
                  children: [{
                      _id: '3',
                      translations: {
                        language: 'string',
                        title: 'Véhicule et engins',
                      },
                      planPrincipal: false,
                      megaMenu: false,
                      icon: 'fa-solid fa-car',
                      path: 'string',
                      taxonomy : 'Véhicule et engins',
                      ordre: 0,
                      priorite: 0,
                      parent: null ,
                      children: [],
                  }],
                },
                {
                  _id: '4',
                  translations: {
                    language: 'string',
                    title: 'code_8809',
                  },
                  planPrincipal: false,
                  megaMenu: false,
                  icon: "fa-solid fa-user-tie" ,
                  path: 'string',
                  taxonomy : 'code_8809',
                  ordre: 0,
                  priorite: 0,
                  parent: null ,
                  children: [],
                },
                {
                  _id: '5',
                  translations: {
                    language: 'string',
                    title: 'code_8810',
                  },
                  planPrincipal: false,
                  megaMenu: false,
                  icon: "fa-solid fa-laptop",
                  path: 'string',
                  taxonomy : 'code_8810',
                  ordre: 0,
                  priorite: 0,
                  parent: null ,
                  children: [],
                },
                {
                  _id: '6',
                  translations: {
                    language: 'string',
                    title: 'code_8811',
                  },
                  planPrincipal: false,
                  megaMenu: false,
                  icon: "fa-solid fa-landmark" ,
                  path: 'string',
                  taxonomy : 'code_8811',
                  ordre: 0,
                  priorite: 0,
                  parent: null ,
                  children: [],
                },
                {
                  _id: '7',
                  translations: {
                    language: 'string',
                    title: 'code_8812',
                  },
                  planPrincipal: false,
                  megaMenu: false,
                  icon: 'fa-solid fa-bolt',
                  path: 'string',
                  taxonomy : 'code_8812',
                  ordre: 0,
                  priorite: 0,
                  parent: null ,
                  children: [],
                },
                {
                  _id: '8',
                  translations: {
                    language: 'string',
                    title: 'code_8813 ',
                  },
                  planPrincipal: false,
                  megaMenu: false,
                  icon: "fa-solid fa-gears",
                  path: 'string',
                  taxonomy : 'code_8813',
                  ordre: 0,
                  priorite: 0,
                  parent: null ,
                  children: [],
                },
                {
                  _id: '9',
                  translations: {
                    language: 'string',
                    title: 'code_8813 ',
                  },
                  planPrincipal: false,
                  megaMenu: false,
                  icon: "fa-solid fa-shop",
                  path: 'string',
                  taxonomy : 'code_8813',
                  ordre: 0,
                  priorite: 0,
                  parent: null ,
                  children: [],
                },      {
                  _id: '10',
                  translations: {
                    language: 'string',
                    title: 'code_8813 ',
                  },
                  planPrincipal: false,
                  megaMenu: false,
                  icon: "fa-solid fa-pen-nib",
                  path: 'string',
                  taxonomy : 'code_8813',
                  ordre: 0,
                  priorite: 0,
                  parent: null ,
                  children: [],
                },      {
                  _id: '11',
                  translations: {
                    language: 'string',
                    title: 'code_8813 ',
                  },
                  planPrincipal: false,
                  megaMenu: false,
                  icon: "fa-solid fa-gears",
                  path: 'string',
                  taxonomy : 'code_8813',
                  ordre: 0,
                  priorite: 0,
                  parent: null ,
                  children: [],
                },
                {
                  _id: '12',
                  translations: {
                    language: 'string',
                    title: 'code_8813 ',
                  },
                  planPrincipal: false,
                  megaMenu: false,
                  icon: "fa-solid fa-gears",
                  path: 'string',
                  taxonomy : 'code_8813',
                  ordre: 0,
                  priorite: 0,
                  parent: null ,
                  children: [],
                },      {
                  _id: '13',
                  translations: {
                    language: 'string',
                    title: 'code_8813 ',
                  },
                  planPrincipal: false,
                  megaMenu: false,
                  icon: "fa-solid fa-gears",
                  path: 'string',
                  taxonomy : 'code_8813',
                  ordre: 0,
                  priorite: 0,
                  parent: null ,
                  children: [],
                },      {
                  _id: '14',
                  translations: {
                    language: 'string',
                    title: 'code_8813 ',
                  },
                  planPrincipal: false,
                  megaMenu: false,
                  icon: "fa-solid fa-gears",
                  path: 'string',
                  taxonomy : 'code_8813',
                  ordre: 0,
                  priorite: 0,
                  parent: null ,
                  children: [],
                },      {
                  _id: '15',
                  translations: {
                    language: 'string',
                    title: 'code_8813 ',
                  },
                  planPrincipal: false,
                  megaMenu: false,
                  icon: "fa-solid fa-gears",
                  path: 'string',
                  taxonomy : 'code_8813',
                  ordre: 0,
                  priorite: 0,
                  parent: null ,
                  children: [],
                },      {
                  _id: '16',
                  translations: {
                    language: 'string',
                    title: 'code_8813 ',
                  },
                  planPrincipal: false,
                  megaMenu: false,
                  icon: "fa-solid fa-gears",
                  path: 'string',
                  taxonomy : 'code_8813',
                  ordre: 0,
                  priorite: 0,
                  parent: null ,
                  children: [],
                },      {
                  _id: '17',
                  translations: {
                    language: 'string',
                    title: 'code_8813 ',
                  },
                  planPrincipal: false,
                  megaMenu: false,
                  icon: "fa-solid fa-gears",
                  path: 'string',
                  taxonomy : 'code_8813',
                  ordre: 0,
                  priorite: 0,
                  parent: null ,
                  children: [],
                },
  ];
  }

  getAllDomains(): Menu[] {
    return this.menu;
  }

  getDomainById(id: 'string'): Menu | undefined {
    return this.menu.find((d) => d._id === id);
  }

}
